{
    "name": "FACODI AI",
    "summary": "Reusable AI services for FACODI and Odoo Community",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "author": "FACODI",
    "depends": ["base", "base_setup", "web"],
    "external_dependencies": {"python": ["pydantic_ai"]},
    "data": [
        "security/facodi_ai_security.xml",
        "security/ir.model.access.csv",
        "data/provider_data.xml",
        "views/provider_views.xml",
        "views/connection_views.xml",
        "views/profile_views.xml",
        "views/prompt_views.xml",
        "views/request_views.xml",
        "views/dashboard_views.xml",
        "views/menu.xml",
        "views/res_config_settings_views.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
